name: CI

on:
  - push
  - pull_request

jobs:
  # See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-running-a-job-within-a-container
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/v-morello/psrchive:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make tests
