name: CI

on:
  - push
  - pull_request

jobs:
  # See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-running-a-job-within-a-container
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/v-morello/psrchive:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test

  publish-to-pypi:
    # Inspired by: https://stackoverflow.com/a/73385644
    # Only run when a git tag is pushed
    if: startsWith(github.event.ref, 'refs/tags/')
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/v-morello/psrchive:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pre-requisites
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build wheel
        # NOTE: build creates a .egg-info directory which interferes
        # with the pip install command in next step
        run: |
          python -m build
          rm -rf *.egg-info
      - name: Install wheel
        run: pip install dist/*.whl
      - name: Test wheel
        run: |
          clfd --despike example_data/psrchive_example.ar
          ls example_data/psrchive_example.ar.clfd
          ls example_data/psrchive_example_clfd_report.json
          ls example_data/psrchive_example_clfd_report.png
      - name: Upload to PyPI
        run: twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*.whl
